version: '3'

services:
  db:
    build: ./.docker/db
    container_name: 'react-express-mysql'
    expose:
      - '3306'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ="Asia/Tokyo"
    volumes:
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/db/database:/var/lib/mysql
      - ./.docker/db/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: 'react-express-mysql-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8081:80
